basic.showString("Hello, I am a member of")
basic.showNumber(5)
basic.showString("nited.")
basic.showString("My name is Ruth Solero.")
basic.showString("My Class Number is")
basic.showNumber(38)
basic.showString("The color I like the most is red")
basic.showString("My favorite subject is arts. My hobbies are drawing and gaming.")
basic.showString("My favorite number is")
basic.showNumber(100)
